# Generated by Django 5.0.6 on 2024-06-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/%Y/%M'),
        ),
        migrations.AddField(
            model_name='contato',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
